language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: Xa7Ud2FZnUz55bBSkcbHkpB5jgOxH+DzjDv9AdMBpfuTu+KVVaPypHH5SPWBpKtBKRPnyiygFqDBIu0tGpJwLXZ50rvwNeNxvy+TTjNCUC+qXtKp7zhl4ZKauv2+NXT+kSNaLmzv76me+qOrmyfPSUgY+CYLzEs2qHa8oa8BwXtYbBxiSugluatG8jAGpASS68REm5JePM0DbxMUnB5cDJ34uN5AVOA2S/Pk/BC/CsbW8HJ84kplolRP+Xnf8o+cgEou5ziQj7pCdCiJ3lVjbw+vOrsNoGm181Ru2UTJoj5OvJgG4xtkWnWNTzkVa7EykXcfDGaRAz+QZdOAfYqc3oPgffaprI4GiK/sS6QwdGyjftFvZtxGoM1CVU/38jmwlEYiI94mw+5oLGhq27HxiV++46/jt2pb6x54wSHdbEzf5fLaltuJB0s2mcaySC+vC/d5TGOpouNm4k3sssz2l8WYae6nrqpLEYlzXvP0rX0905xgx3I3lajAWl6wW01jfcf7KmevuH5G0OzEI0kjmoMllIedRyoBnBD8nl01N63U4MO7/2CM7wzENOlTF4LA3yh/Q8Dwprstj7/sKKhGNdHr4Kw0aNd+ZU+ckMYx93CzH76Cvz8LmNmDk7N3nl6Lja8BaS87GLtI8E+t7ONE6f9h1JYhPsp7KH4k+SSivX0=
